name: Tests
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v4
      
      - name: Install dependencies
        run: uv sync --all-extras --dev
      
      - name: Run tests
        run: pytest tests
